"""Type aliases and constants for tokenstats."""

from typing import Protocol
from models import Session, Message


class SessionProvider(Protocol):
    """Protocol for session providers."""
    
    @classmethod
    def detect(cls) -> bool: ...
    
    @classmethod
    def list_sessions(cls) -> list[Session]: ...
    
    @classmethod
    def get_messages(cls, session_id: str) -> list[Message]: ...


# Session field annotations for documentation
SESSION_FIELD_DOCS = {
    "id": "Unique session identifier",
    "title": "Session title or description", 
    "provider": "Provider name (opencode, claude, cursor, etc.)",
    "input_tokens": "Tokens consumed by prompts/prefills",
    "output_tokens": "Tokens generated by the model",
    "reasoning_tokens": "Computation tokens for model thinking",
    "cache_read": "Cached tokens reused from cache",
    "cache_write": "Tokens written to cache",
    "cost": "Cost in hundred-millionths of a dollar (e.g., 1 = $0.00000001)",
    "steps": "Number of assistant messages in session",
    "model": "Model name/identifier",
    "project": "Project directory or workspace name",
    "time_created": "Unix timestamp in milliseconds",
}

MESSAGE_FIELD_DOCS = {
    "session_id": "Parent session ID",
    "role": "Message role (assistant/user/system)",
    "input_tokens": "Input tokens for this message",
    "output_tokens": "Output tokens generated",
    "reasoning_tokens": "Reasoning/computation tokens",
    "cache_read": "Cached tokens read",
    "cache_write": "Cached tokens written",
    "cost": "Step cost in microdollars",
    "finish_reason": "Completion reason (stop/max_tokens/etc)",
    "time_created": "Creation timestamp in milliseconds",
    "time_completed": "Completion timestamp in milliseconds",
}
